### ISSUE TITLE
Bot posting updates multiple times

### ISSUE THREAD

**Issue by Halatan** [jckli/mangaupdates-bot#42]
Since 20th of November for me, the bot posts updates to my server multiple times: 

- On November 20th, I've received 18 updates on V.5 C.24 for [Citrus+](https://www.mangaupdates.com/series/v57h7ia/citrus)
- On November 21st, I've received 6 updates on C.27 for [Kanan-sama wa Akumade Choroi](https://www.mangaupdates.com/series/5yoo9wh/kanan-sama-wa-akumade-choroi)
- On November 21st, I've received 6 updates on C.28 for [Saotome-san ni wa Mou Death Game Shikanai](https://www.mangaupdates.com/series/tsjgpxw/saotome-san-ni-wa-mou-death-game-shikanai)
- On November 22nd, I've received 7 updates on C.112 for [Chainsaw Man](https://www.mangaupdates.com/series/ylx5wzn/chainsaw-man)
- On November 22nd, I've received 7 updates on C.112 for [Dosanko Gyaru ha Namaramenkoi](https://www.mangaupdates.com/series/yx8zva8/dosanko-gyaru-ha-namaramenkoi)

**Comment by jckli** [comment]
November 20th, I tried to fix the error, which turns out was due to mangaupdates.com sending me different urls occasionally. That one was fixed (I believe at least)

I actually did not know about the multi updating for yesterday and today. Thanks for the issue. I will start debugging as soon as I can.

Sorry for the inconveniences. mangaupdates.com api is kinda funky and that messes up my bot. Will update here when I find out the issue.

**Comment by jckli** [comment]
It seems like it has been fixed, as I haven't seen anything about multiple updates (at least within the error logs and within my own personal manga updates). Yes, I do use the bot myself LOL

With that being said, I'm going to close this issue for now. Please open it back up again if you see anything again. Thanks!
